refactor settings
bug fix: django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: store
- refactored 'store' to 'store.EcommerceSiteConfig', removed duplicate value

bug fix: django.core.exceptions.ImproperlyConfigured: 'basket.apps' does not contain a class 'EcommerceSiteConfig'. Choices are: 'BasketConfig'.
- refactored duplicate EcommerceSiteConfig to BasketConfig

bug fix: ModuleNotFoundError: No module named 'django_ecommerce_tut'
- refactored 'django_ecommerce_tut' to core in setting.py

bug fix: AttributeError: module 'basket.views' has no attribute 'basket'
- typo . instead of _

bug fix: django.template.exceptions.TemplateDoesNotExist:
- changed return url in basket summary to the basket dir in templates